# server/render.yaml - WORKING VERSION
services:
  - type: web
    name: smart-contract-security-backend
    runtime: node
    plan: starter
    buildCommand: |
      # Install Node.js dependencies
      npm install
      
      # Install Slither in user space (no sudo needed)
      pip3 install --user slither-analyzer
      
      # Verify installations
      echo "== Verification =="
      node --version
      npm --version  
      python3 --version
      pip3 --version
      ~/.local/bin/slither --version
      echo "=== Build Complete ==="
      
    startCommand: npm start
      
    healthCheckPath: /health
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: PATH
        value: /home/render/.local/bin:/usr/local/bin:/usr/bin:/bin
      - key: FRONTEND_URL
        sync: false
      - key: INFURA_RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: RISK_THRESHOLD
        value: 7.0